### ISSUE TITLE
Issue rending admin tree view for Materialized Paths

### ISSUE THREAD

**Issue by Ryanb58** [django-treebeard/django-treebeard#118]
I am running into a stack trace when heading to the Django admin in 2.1.. but when I downgrade to 2.0.8 I am able to do anything I need to just fine.I am curious to if anyone else has been experiencing this issue as well? 

```
Internal Server Error: /admin/attraction/attraction/45/change/
Traceback (most recent call last):
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/template/loader_tags.py", line 188, in render
    return template.render(context)
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/template/base.py", line 993, in render
    return render_value_in_context(output, context)
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/template/base.py", line 972, in render_value_in_context
    value = str(value)
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/utils/html.py", line 397, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/forms/boundfield.py", line 33, in __str__
    return self.as_widget()
  File "/home/ryanb58/github/wdw-itinerary/backend/venv/lib/python3.5/site-packages/django/forms/boundfield.py", line 93, in as_widget
    renderer=self.form.renderer,
TypeError: render() got an unexpected keyword argument 'renderer'
```

**Comment by jrief** [comment]
did Django's API change from 2.0 to 2.1 in this respect. Did you read their release notes?

**Comment by 4levels** [comment]
Hi @Ryanb58,

your stack trace shows that not a single file of this repository is hit, hence this problem has nothing to do with django-treebeard.  Please close this issue. As @jrief already suggested, there are some breaking changes when upgrading to 2.1, please see the changelog here (search for `renderer`): https://docs.djangoproject.com/en/2.1/releases/2.1/
